# config/federated_local.yaml
# Configuration file for local environment

data:
  # Choose bot_iot or mnist
  name: bot_iot

  # Bot-IoT CSV path (local environment)
  path: "data/raw/Bot-IoT"

  # Number of clients
  num_clients: 4

  # Limit sample size if too large (can be increased if needed)
  max_samples: 200000

model:
  # mlp or cnn (usually mlp for Bot-IoT)
  name: mlp

federated:
  num_rounds: 3

  # Fraction of clients participating in each round (1.0 = all clients)
  fraction_fit: 1.0
  fraction_evaluate: 1.0

  # Local training settings
  local_epochs: 2
  batch_size: 128

  # Reserved for strategy internal use
  min_fit_clients: 4
  min_evaluate_clients: 4
  min_available_clients: 4

